### ISSUE TITLE
Idea: automatically tag parameters with @Named based on source code names

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#142]
Consider the following class:

```kotlin
@SomeScope class Generator(val outputDirectory: Path)
```

This is not going to be a good idea, because `Path` is too generic to be a DI injectable thing unless you only have one of them, which seems like a risky assumption to make in an evolving codebase. A better way is:

```kotlin
@SomeScope class Generator(@Named("outputDirectory") val outputDirectory: Path)
```

But this is quite redundant. I have to specify the name twice. In Java this sort of thing was once required, because reflection didn't expose parameter names, so people got used to do things this way. Nowadays reflection does expose it if you pass `-parameters`, Kotlin always does, and of course AI doesn't use reflection anyway.

I'm curious if anything would stop AI automatically adding names from the source code if no other `@Named` annotation is present. As far as I can tell, this would be backwards compatible because if a constructor param doesn't already have such an annotation, then it's got to be matching based on type anyway, so the name seems kind of redundant.

**Comment by rbygrave** [comment]
>  if anything would stop AI automatically adding names from the source code if no other @Named annotation is present.

Well, at the moment avaje-inject breaks on this as it tries to match the qualifier name BUT ... it could change to only match on the qualifier name IF there is more than one candidate to choose from.  That is, when there is only one `Path` candidate then it shouldn't matter if we are attempting with a name qualifier or not  

So I don't see why both should not work:
```
val outputDirectory: Path // only works if there is one and only one candidate

@Named("outputDirectory") val outputDirectory: Path  // only use the qualifier name when there is more than one candidate
```
I think the only issue is if this is unexpected behaviour.


Also note that I think we have a somewhat related bug in that the below should probably work but doesn't, it isn't in the TCK tests ... hmmm. 
```
@Named val outputDirectory: Path  // only use the qualifier name when there is more than one candidate
```

**Comment by rbygrave** [comment]
Ok, we can we do this.

```java
  public MyAutoB2(AutoB2 one, AutoB2 two) {
    this.one = one;
    this.two = two;
  }
```
We can add implied qualifier names to the above so it is (*almost) like the below.

```java
  public MyAutoB2Explicit(@Named("one") AutoB2 one, @Named("two") AutoB2 two) {
    this.one = one;
    this.two = two;
  }
```
### (*almost)

What AI does is instead of names `one` and `two` it gives them names `!one` and `!two` with the leading `!` telling AI they are _implied names_ that were added implicitly.

The search for a candidate when using _implied names_  is:
1. Search for a candidate using the implied name first 
2. If no match is found, search again for a candidate as if NO name was (name = null)

### Feature benefits

There are some nice benefits to this feature in that it reduces verbosity plus it better handles the case where we go from having a single candidate for a type to having multiple and then need to used named qualifiers. With this feature we often might only require `@Named` on the "source" factory bean methods etc and not on all the "target" places (constructors).

So yes, a pretty darn good idea I'd say!!


----
### Generated code example

We see the `!` leading character in qualifier name - tells us they are _implied_ names.


```java
@Generated("io.avaje.inject.generator")
public class MyAutoB2$DI  {

  /**
   * Create and register MyAutoB2.
   */
  public static void build(Builder builder) {
    if (builder.isAddBeanFor(MyAutoB2.class)) {
      MyAutoB2 bean = new MyAutoB2(builder.get(AutoB2.class,"!one"), builder.get(AutoB2.class,"!two"));
      builder.register(bean);
    }
  }

}

```

### Factory methods too

This applied to factory methods as well as constructors.  For example:

```java
  @Bean(initMethod = "init", destroyMethod = "close")
  BFact buildB(AFact afact, CoffeeMaker maker) {
    return new BFact(afact, maker);
  }
```
We see the `"!afact"` and `"!maker"`

```java
    if (builder.isAddBeanFor(BFact.class)) {
      Configuration factory = builder.get(Configuration.class);
      BFact bean = factory.buildB(builder.get(AFact.class,"!afact"), builder.get(CoffeeMaker.class,"!maker"));
      ...
    }
```

**Comment by mikehearn** [comment]
Nice!

**Comment by rbygrave** [comment]
See also https://github.com/avaje/avaje-inject/issues/144 ...
