### ISSUE TITLE
6.11 not pushed to master

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#149]
I upgraded to 6.11 and this time it works! Super! 

I noticed it was released but not pushed to git. Once the docs are updated (I just opened a PR) and the code is pushed, I guess the upgrades are all completed.

**Comment by rbygrave** [comment]
> but not pushed to git

Dang, yes I forgot that - pushed it now plus a bump to the next snapshot version.  I've been just using maven deploy rather than the release plugin recently and missed a step there - thanks for picking that up.

I've merged the docs update.  I'll go through the docs again shortly, maybe need more examples on custom scopes etc.

Thanks, Rob.
