### ISSUE TITLE
What is prototype scope?

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#192]
The docs don't say and I couldn't figure it out by looking at the change.

**Comment by rbygrave** [comment]
> what is prototype scope

A new instance of this bean will be created each time it is requested or wired.

That is, say we have MyProto and it is injected into MySingle1 and MySingle2 ... then there are 2 different instances of MyProto created and injected into MySingle1 and MySingle2 - not the same instance of MyProto.


> what is it used for ?

It's use is expected to be extremely rare. For example, in my career to date I have never ever used prototype scope - not once!! This isn't just me, there are discussions on stackoverflow on this which similarly state that it isn't used.

That said, the case where I think it _could_ be used is where a library is built that uses avaje-inject and allows users of the library to customise it using injection AND for some rare case that the customization component needs to be prototype scope (has state per injection).  

That is, in general _direct_ use of avaje-inject isn't going to need it because the alternative of just programmatically using `new` is arguably easier and better. I only really expect it's use in the case where there is a project customizing the use of a third party library that uses avaje-inject (and a need for _state per injection_).  


> why add it if it is so extremely rare to need it ?

Well it didn't add much complexity and it's one of those features where if you really need it then it might be hard to get a good workaround without it.  It's really a guess on my part that it will be useful to someone at the 11th hour when they go "oh darn, this component has certain state that means I need prototype scope" and they are too far removed code wise to just programmatically use `new` or otherwise get a decent workaround.


> The docs 

The docs have got behind on:
- Prototype scope
- Use of `@TestScope` for component testing
- Use of AOP Aspects

I have an outline of "tutorials" that I think I should probably do at https://avaje.io/inject/tutorials

Docs are my kryptonite :(

**Comment by rbygrave** [comment]
Oh, I think I can close this @mikehearn
