### ISSUE TITLE
@Nullable not working?

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-inject#244]
The following fails to compile.
```
@Singleton
class Pump {

  private final Widget widget;

  @Inject
  Pump(Optional<Widget> widget) {
    this.widget = widget.orElse(new Widget());
  }

  public void pump() {
    widget.doStuff();
  }

  public record Widget() {

    public void doStuff() {}
  }
}
```
I'm getting the classic. 
```
Dependencies [Widget] are not provided - missing @Singleton, @Component, @Factory/@Bean or specify external dependency via @InjectModule requires attribute
```

**Comment by rbygrave** [comment]
I believe the correct behavior is to have the compiler error and instead the expectation is that `Widget` be it optional or not is provided externally either programmatically via another module.

That is, when compiling the injection dependencies and `Widget` is an **_external_** dependency that is expected to be provided then we should specify that via `@InjectModule(requires = Widget.class)` - see https://avaje.io/inject/#single-module

**Comment by SentryMan** [comment]
So what's the use in having @Nullable if the value can't be null? I thought the intent was to mimic the functionality of Spring's @Autowired(required=false). 

From the Docs.
>Spring users will be familiar with the use of @Autowired(required=false) for wiring optional dependencies. With avaje->inject we instead use Optional or @Nullable to inject optional dependencies

**Comment by rbygrave** [comment]
There are 2 cases of nullable.

1. It's nullable and the dependency is optionally provided by THIS module

2. It's nullable and the dependency is EXTERNALLY provided


The case we are talking about here is 2 ... where we are saying it is
EXTERNALLY provided ... and what we are saying here is that being
*EXTERNALLY* provided is more important (trumps) it being nullable.

If Widget isn't actually externally provided then there is an error here
and we need to include Widget in the wiring (like add it via a  @Factory @Bean
method).

If Widget is externally provided then this impacts wiring order across
modules.

Spring doesn't worry about this because 1) it just becomes a runtime error
for them and 2) the determine ALL the wiring order at runtime across all
modules.

Does any of that make sense?


So Nullable/Optional IS the same as Spring Autowired(required=false) but
that isn't taking into account if this is an externally provided dependency
(where we should say so explicitly) or a wiring error where we have
forgotten to include Widget as a component that we wire.

Was the intention that Widget was an external dependency?

**Comment by SentryMan** [comment]
For those two scenarios, I get what you're saying. But I'm thinking about a possible scenario 3, where we want to have a truly optional dependency and have some logic based on its presence. Perhaps this doesn't happen that much, but that's what I'm thinking about.

 I had a minor inconvenience where I wanted to have a nullable list of a certain interface (It was to be implemented at a later time). I basically had to create a dummy implementation and wire that.

**Comment by rbygrave** [comment]
> and have some logic based on its presence

That is expected and that logic is expected to be in a `@Factory @Bean` method - see https://avaje.io/inject/#optionalBean

This being a compile error is trying to say ... we are expecting to have a `@Factory @Bean` method that provides Widget as Optional but that is missing.

**Comment by SentryMan** [comment]
ok
