### ISSUE TITLE
Support Qualified Lists/Set

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-inject#289]
Suppose we want a list of qualified beans.
```
@Qualifier
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE_USE)
public @interface Listener {}


@Inject
public void registerListeners(Set<@Listener ListenerInterface> foundListeners) {
//whatever
}
```
Currently, this won't work.

**Comment by SentryMan** [comment]
Hmm, I wonder if we need this since we have the qualified map changes.

**Comment by rbygrave** [comment]
I don't understand the use case in that the qualifier + type is expected to be unique. 

Can you explain the use case more?  What are the other qualifiers apart from the `@Listener` qualifier?

**Comment by Tim203** [comment]
> the qualifier + type is expected to be unique

I wasn't able to find that in Avaje Inject a Qualifier is supposed to be unique.
I see a qualifier as some kind of if statement that limits but doesn't necessarily require a single bean.

I'm not sure what you mean with 'what are the other qualifiers'.
A class of an event listener looks as follows:
```java
@Listener
public class LifecycleListener {
  @Subscribe
  public void onShutdown(ShutdownEvent ignored) {}
}
```
Supporting qualified lists/sets would allow them to be registered easily (instead of using `BeanScope#listbyAnnoation(Class)`)

**Comment by SentryMan** [comment]
> I see a qualifier as some kind of if statement that limits but doesn't necessarily require a single bean.

`@Qualifier` seems to be just another form of `@Named` without using a string literal.  

> (instead of using BeanScope#listbyAnnoation(Class))

Ahhh ok, now I understand. The actual feature request is to basically do listByAnnotation at build time. Even with the PR I made, you couldn't actually get types that don't extend a common interface, I'll see if I can add something like that.

**Comment by rbygrave** [comment]
> I wasn't able to find that in Avaje Inject a Qualifier is supposed to be unique.

I'd suggest its more assumed knowledge of Jsr-330 (and spring di). We could add it to the docs but i don't see this as avaje-inject specific. Note that JSR-330 does have a test suite that avaje-inject passes. Otherwise avaje-inject extends JSR-330 with Spring DI features (primary, secondary,  factory etc all come from Spring DI).

Is the suggestion that guice supports something like this? 

> @Qualifier seems to be just another form of @Named without using a string literal.

Exactly right.

> Ahhh ok, now I understand. The actual feature request is to basically do listByAnnotation at build time

It is not clear what the use case is here. This returns a List<Object> So the target of that List is going to be doing reflection or something?

**Comment by SentryMan** [comment]
Seems like there shouldn't be a situation where multiple classes of the same type share a qualifier, closing this
