### ISSUE TITLE
Custom scope is ignored for Factory Beans

### ISSUE THREAD

**Issue by Tim203** [avaje/avaje-inject#304]
```java
@Factory
public class AFactory {
  @Bean
  @ACustomScope
  Hello hello() {}

  @Bean
  @BCustomScope
  ExtendsHello extendsHello() {}
}
```
(where ExtendsHello extends Hello)
Both are registered regardless whether any of the scopes are added as a module.

This leads to problems e.g. where you'd expect one binding of Hello, but instead there are two registered: Hello & ExtendsHello

**Comment by rbygrave** [comment]
When we put the `@BCustomScope` on the AFactory itself we should get the result we are after - and this is what I'd expect assuming all the beans the factory creates are expected to be in the custom scope.

So:

```java
@BCustomScope
@Factory
public class AFactory {
  @Bean
  Hello hello() {}

  @Bean
  ExtendsHello extendsHello() {}
}


```

**Comment by SentryMan** [comment]
He has 2 custom scopes. Depending on which custom module he adds he wants to wire a certain factory bean.

**Comment by SentryMan** [comment]
![image](https://user-images.githubusercontent.com/32279667/221969647-260920e1-5d45-44ec-8dc9-7e10e57429b5.png)

**Comment by rbygrave** [comment]
Mike is a big user of custom scopes in a "build application". For that application there is a base custom scope for "all platforms" and then custom scopes for windows, linux, mac etc ... the custom scopes form a hierarchy.  When the build application starts it determines the platform it's building for and then uses the appropriate custom scopes. For example, when building on linux the windows custom scope is not used at all.

The question here is, **_why isn't `@BCustomScope` on the factory_** rather than putting it on each bean.  Putting the scope on each `@Bean` implies the factory _could_ produce beans for different scopes and that isn't something we want - we want the factory to only build beans for a single scope.

**Comment by SentryMan** [comment]
> we want the factory to only build beans for a single scope.

alrighty then

**Comment by Tim203** [comment]
> The question here is, **_why isn't `@BCustomScope` on the factory_** rather than putting it on each bean. 

The reason for that is because that factory only generates one bean depending on the platform (maybe I should've called the factory `HelloFactory`). That's why specifically mentioned the `ExtendsHello`. `Hello` is the base class and is enough for the majority of the classes, but some classes need the additional context of the `ExtendsHello` (which is only used when `@BCustomScope` applies.)

> Putting the scope on each `@Bean` implies the factory _could_ produce beans for different scopes and that isn't something we want - we want the factory to only build beans for a single scope.

I'm not asking to specify the scope of every bean of every factory, but only for the ones that need a different scope.
I'm also fine with it being a limitation of Avaje Inject, but in that case it'd be nice to write that limitation down somewhere in the documentation.

**Comment by rbygrave** [comment]
> factory only generates one bean depending on the platform

Can you put up an example that is more concrete - not using Hello, ACustomScope, Foo etc but something that represents what is practically being done here and reflects what is the actual use case we face. Does this factory also create beans in the "default scope"? are there cross scope dependencies in the wiring? What is the relationship between the scopes? etc.

I want to more clearly understand the use case that brought this issue up. I want to see is this is a "new pattern" that justifies a change to allow it or if it's a "pattern that we want to actively discourage". At the moment I don't understand the use case clearly enough.

Thanks, Rob.

**Comment by Tim203** [comment]
The class that needs converting is [ConfigLoader](https://github.com/GeyserMC/Floodgate/blob/2230f2a6d3b01f2547933d3caa4626678ad5c602/core/src/main/java/org/geysermc/floodgate/config/ConfigLoader.java).
Currently `ConfigLoader#load()` is called in the [CommonModule](https://github.com/GeyserMC/Floodgate/blob/2230f2a6d3b01f2547933d3caa4626678ad5c602/core/src/main/java/org/geysermc/floodgate/module/CommonModule.java#L123) and is being casted to the proxy version (which has additional fields over the default backend server config) in the [ProxyCommonModule](https://github.com/GeyserMC/Floodgate/blob/2230f2a6d3b01f2547933d3caa4626678ad5c602/core/src/main/java/org/geysermc/floodgate/module/ProxyCommonModule.java#L53), which is only loaded for proxy platforms.
Given that multiple beans should have a different implementation depending on whether they're a proxy platform, I thought that it'd be nice to have a `@ServerScope` and `@ProxyScope`.

One place where I'm already using it and I believe that it works is [SimpleFloodgateApi](https://github.com/GeyserMC/Floodgate/blob/2230f2a6d3b01f2547933d3caa4626678ad5c602/core/src/main/java/org/geysermc/floodgate/api/SimpleFloodgateApi.java) which is the base implementation of FloodgateApi for server platforms. That class got the `@ServerScope` annotation. The proxy version of the FloodgateApi, [ProxyFloodgateApi](https://github.com/GeyserMC/Floodgate/blob/2230f2a6d3b01f2547933d3caa4626678ad5c602/core/src/main/java/org/geysermc/floodgate/api/ProxyFloodgateApi.java), extends SimpleFloodgateApi and gets the `@ProxyScope` annotation.

The ConfigLoader is a bit harder since it depends on a config loading library, and the returning class depends on whether it's a proxy platform or not. Most classes depend on FloodgateConfig, but some proxy classes need ProxyFloodgateConfig. I wouldn't have needed the scopes for this specific class if Avaje Inject looked at the class three of the returned instance, but Avaje Inject is compile time so that wouldn't really work.

The idea I had was to make ConfigLoader a factory, something like:
```java
@Factory
public final class ConfigLoader {
  @Bean
  @ServerScope
  FloodgateConfig serverConfig() {
    return load(FloodgateConfig.class);
  }
    
  @Bean
  @ProxyScope
  ProxyFloodgateConfig proxyConfig() {
    return load(ProxyFloodgateConfig.class);
  }

  // load method
}
```
This idea would result in`proxyConfig` binding to both ProxyFloodgateConfig and FloodgateConfig, and `serverConfig` only FloodgateConfig.

**Comment by SentryMan** [comment]
We conditional beans so not sure if this is really needed anymore.

**Comment by rbygrave** [comment]
Ok cool. Worth keeping open for a while and I'll try to have a look at this. As I see it, if we can manage to support this without adding to much internal complexity then it would be worth it given that people will similarly try to do this going forward.

**Comment by rob-bygrave** [comment]
So I had a case of using "conditional wiring" via `@RequiresProperty` and it got me thinking about `profiles` (and profiles were recently added to avaje-config) and specifically about Spring DI profiles as a form of "conditional wiring" - https://www.baeldung.com/spring-profiles

Now, the example imo BAD because in my mind `profiles` is NOT about dev/test/prod environment but more like this case of "proxy profile/scope" vs "server profile/scope".

In some ways "profiles" is a simple alternative to using avaje-inject scopes.  Where avaje-inject scopes are hierarchical and compile time checked etc.  Profiles are just "conditional wiring" where it is still a single flat BeanScope.

In some ways "profiles" are like  `@RequiresProperty` ... almost a special kind of require property.

-----
Now, Spring folks are familiar with using Spring profiles in a "conditional wiring" way and it seems to me that it would be good to have basically the same feature. There is decent overlap with avaje-inject scopes, but I think that is still ok (scopes are still very cool - we have our special test scope etc).

If we had "profiles" that might have been a nice simple "conditional wiring" option that could have been used here.

**Comment by SentryMan** [comment]
I can add, do you want me to reuse the same Config profiles property name?

**Comment by rob-bygrave** [comment]
> I can add

Awesome !!


> the same Config profiles property name?

Well I was thinking that it might be better to use `avaje.profiles` / `AVAJE_PROFILES` for both avaje-inject and avaje-config. That would mean avaje-config might need to _also_ support the existing `config.profiles` / `CONFIG_PROFILES` (and we could deprecate that at some future time).

What do you think?

**Comment by SentryMan** [comment]
For factories, I think the conditional wiring constructs we added take care of this use case. We can take another look later if somebody else needs this.
